setting_icon='//ul[@class="sidebar-menu tree"]/li[@class="treeview"]//i[@class="fa fa-fw fa-gear "]'
user_text='//ul[@class="treeview-menu"]//a[@href="https://test.legacyconsole.gozwing.com/admin/staff/view"]'
user_page='//h3[@class="box-title m-0"]'
new_user_btn='//button[@class="btn btn-primary" and text()="+ New User"]'
new_user_page='//h4[text()="New user"]'
select_store_check_btn='(//label[@class="checkbtn fs-13"])[2]'
assign_role_drop_down='//div[@class="multiselect__tags"]'
cashier_option='//ul[@id="listbox-null"]/li[@id="null-1"]//span[text()="Cashier"]'
first_name_text_box='//input[@placeholder="First Name"]'
last_name_text_box='//input[@placeholder="Last Name"]'
username='//div/input[@placeholder="User Name"]'
email_id_text_box='//input[@placeholder="Email"]'
phone_no_text_box='//input[@placeholder="Phone"]'
pass_text='//div/input[@placeholder="Password"]'
confirm_pass_text_box='//input[@placeholder="Confirm Password"]'
employee_code_text_box='//input[@placeholder="Enter Employee Code"]'
store_search_box='//div[@class="search-box pr-0 w-100"]/input[@class="form-control input-sm"]'
selected_store_code='//tr[@role="row"]/td[@role="cell" and text()=Swap]'
check_box='//tr[@role="row"]/td[@aria-colindex="1"]/input[@class="form-input-check float-none"]'
save_btn='//div[@class="col-md-8"]/button[@class="btn btn-primary pull-right"]'

##user page##
user_text_page='//h3[@class="box-title m-0"]'
verify_username='//tr[@class="collapse show"][1]/td[5]'
